version: '3'

services:
  db-openjuy:
    image: mysql:8.0
    container_name: db-openjuy
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - network-openjuy

  php-openjuy:
    depends_on:
      - db-openjuy
    build: ./.docker/php
    image: php-openjuy
    container_name: php-openjuy
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
    volumes:
      - ./html:/var/www/html
      - ./.php-conf/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - network-openjuy

  nginx-openjuy:
    depends_on:
      - php-openjuy
#    image: nginx:1.15.12-alpine
    build: ./.docker/nginx
    image: nginx-openjuy
    container_name: nginx-openjuy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html:cached
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt
    networks:
      - network-openjuy

volumes:
  certbot-etc:
  html:
  dbdata:

networks:
  network-openjuy:
    driver: bridge
